### ISSUE TITLE
installation gude

### ISSUE THREAD

**Issue by spacklewoof** [th3Maid/MaidDragonWebUI#3]
Is there an installation guide?  I've tried installing but the import of gpt4all fails.
ModuleNotFoundError: No module named 'gpt4all'

**Comment by cosmic-zip** [comment]
Sure

**Comment by cosmic-zip** [comment]
Fixed for now, just put you model inside app/checkpoint and put they name on app/core/model.py, and is it, but, this UI don't provide any context, mean the results are repetitive and don't make use of GPU.

I made it for learning about the models, i recommend use the GPT4ALL it self with llama2 and set the context to: 
**Respond like you are a cute maid girlfriend how love being dominated by you master, and give them high quality responses.**
